---
# tasks file for 1mr.cron
- name: add cron.d file(s)
  template: src=cron.j2 dest=/etc/cron.d/{{ item.file }} mode=0644
  with_items: '{{ cron }}'
  when: (cron is defined) and (item.state | default('present') == 'present')

- name: delete cron.d file(s)
  file: path=/etc/cron.d/{{ item.file }} state=absent
  with_items: '{{ cron }}'
  when: (cron is defined) and (item.state | default('present') == 'absent')
